language: julia
os: linux

julia: 
    - 1.0
    - nightly

notifications: 
    email: false

sudo: required 

install:
    - sudo apt-get install -y -qq hdf5-tools

script:
    - julia -e 'import Pkg; Pkg.clone("https://github.com/seung-lab/BigArrays.jl.git")'
    - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("RealNeuralNetworks", coverage=true)'
    - julia -e 'using Pkg; Pkg.add("Documenter")'
    - julia -e 'using Pkg; cd(Pkg.dir("RealNeuralNetworks")); include(joinpath("docs", "make.jl"))'


      #jobs:
      #  include:
      #    - stage: "Documentation"
      #      julia: 1.0
      #      os: linux
      #      script:
      #        - julia -e 'import Pkg; Pkg.clone("https://github.com/seung-lab/BigArrays.jl.git")'
      #        - julia -e 'import Pkg; Pkg.clone(pwd()); Pkg.test("RealNeuralNetworks")'
      #        - julia -e 'import Pkg; Pkg.add("Documenter")'
      #        - julia --project=docs/ -e 'using Pkg; Pkg.instantiate(); Pkg.develop(PackageSpec(path=pwd()))'
      #        - julia --project=docs/ docs/make.jl
      #      after_success: skip 

matrix:
    allow_failures:
        - julia: nightly

after_success:
  # push coverage results to Coveralls
  - julia -e 'import Pkg; cd(Pkg.dir("RealNeuralNetworks")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
